CONTRIBUTING.md
README.md

feat: add readme and contributing markdown file.

---

src/Assertion.lua

Signed-off-by: Rushikesh Tote <rushi.tote@gmail.com>

Updated Assertion.lua

---

src/Assertion.lua
src/RoleManager.lua

- Added bare bones for RoleManager
- Updated Assertion file

Updated Assertion and added RoleManager

---

src/Adapter.lua
src/FileAdapter.lua
src/util.lua

- Added FileAdapter to load/save policy file from/to storage.

Added FileAdapter and utility functions for it

---

src/config/Config.lua

Added barebone functions in the Config file.

Updated Config.lua

---

src/model/Assertion.lua
src/model/Policy.lua
src/util/Util.lua

Signed-off-by: RobotHuang <1183598761@qq.com>

Add Policy

---

src/effect/DefaultEffector.lua
src/effect/Effect.lua
src/effect/Effector.lua

- Updated Effect
- Added Effector and the DefaultEffector

Added Effect files

---

src/config/Config.lua
src/effect/DefaultEffector.lua
src/util/Util.lua

- Updated Config file and added utility functions for it
- Fixed previous commit's syntax errors

Updated Config file

---

src/model/Policy.lua
src/util/Util.lua
tests/util/test_Util.lua

- Added tests using the [luaunit](https://github.com/bluebird75/luaunit) testing module.
- Fixed errors in the Utility module
This is the test_Util output:
```
..........
Ran 10 tests in 0.002 seconds, 10 successes, 0 failures
OK
```

Added tests for Utility module and fixed errors in it

---

spec/config/config_spec.lua
spec/config/test.ini
spec/util/util_spec.lua
src/config/Config.lua

Ported tests from the previous utility and config test modules which used `luaunit`.

feat: Added utility and config tests with busted library

---

.github/workflows/build.yml
README.md

Signed-off-by: Rushikesh Tote <rushi.tote@gmail.com>

feat: Added badges for GitHub build and test coverage and workflow for reporting test coverage runs

---

.github/workflows/release.yml
.releaserc.json
README.md

feat: Added sematic release feature

---

spec/model/model_spec.lua
spec/persist/saved_policy.csv
spec/rbac/role_manager_spec.lua
spec/util/log_spec.lua
src/model/Model.lua
src/model/Policy.lua
src/rbac/DefaultRoleManager.lua
src/util/Log.lua
src/util/Util.lua

Also added test for the logging module and logging functionality in Model, Policy and Role Manager modules.

feat: Added logging module for logging to console/file

---

examples/abac_multiple_rules_model.conf
examples/abac_multiple_rules_policy.csv
examples/keymatch_policy.csv
spec/main/enforcer_spec.lua
src/main/CoreEnforcer.lua

- Added full tests for CoreEnforcer
- Now the CoreEnforcer can work with empty policies too
Next focus would be on creating a setup guide for OpenResty users.

test: Added CoreEnforcer tests and feat: Enforce with no policy functionality

---

Setup-OpenResty.md
src/main/Enforcer.lua
src/main/InternalEnforcer.lua
src/model/Policy.lua
src/persist/file_adapter/FileAdapter.lua
tests/main/internal_api_spec.lua
tests/model/model_spec.lua

- Added test for Internal API and fixed errors in it.
- Fixed a typo in the setup guide.

feat: Added Internal API test and fix: errors with Internal API

---

src/main/Enforcer.lua
src/main/InternalEnforcer.lua
src/main/ManagementEnforcer.lua
src/model/FunctionMap.lua
src/model/Policy.lua
src/util/Util.lua

Next, I will add tests for this.

feat: Added Management API for the Enforcer

---

src/main/CoreEnforcer.lua
src/main/Enforcer.lua
src/main/InternalEnforcer.lua
src/model/Model.lua
src/model/Policy.lua
src/util/Util.lua
tests/main/enforcer_spec.lua
tests/main/rbac_api_spec.lua

- RBAC API (without domains) was added
- Added functions for `BatchEnforce`, `AddNamedMatchingFunc`, `AddNamedDomainMatchingFunc`
Next, I will add the remaining RBAC API (with domains) and then RBAC API tests.

feat: Added RBAC API

---

src/effect/DefaultEffector.lua
src/main/CoreEnforcer.lua
src/main/InternalEnforcer.lua
src/persist/Dispatcher.lua
src/persist/Watcher.lua
src/persist/WatcherEx.lua
src/persist/WatcherUpdatable.lua
src/rbac/DefaultRoleManager.lua
src/util/Log.lua
src/util/Util.lua
tests/main/enforcer_spec.lua
tests/persist/watcher_spec.lua
tests/util/log_spec.lua

- Now, there is a single logger for an Enforcer.
- Also added functionality to save all logs to a specific file.

feat: Added logging, file logging and interfaces for watcher and dispatcher

---

Setup-OpenResty.md

Updated the setup documentation since Casbin has a `.rockspec` now.

fix: setup documentation for Casbin installation

---

src/rbac/DefaultRoleManager.lua
src/rbac/Role.lua
src/util/BuiltInFunctions.lua
tests/main/enforcer_spec.lua
tests/rbac/role_manager_spec.lua

Now the `domainMatchingFunc` of RBAC can be used. Also added the Enforcer tests.

feat: Added RBAC domain pattern functionality with tests

---

src/effect/DefaultEffector.lua
src/effect/Effect.lua

Signed-off-by: 蒋振邦 <edomondja@gmail.com>

feat: add some comment

---

src/config/Config.lua
src/effect/DefaultEffector.lua
src/effect/Effect.lua

feat: Add function newConfigFromText
Signed-off-by: 蒋振邦 <edomondja@gmail.com>

feat: Add function newConfigFromText

---

src/model/Model.lua
tests/model/model_spec.lua

feat: Add function saveModelToText

---

src/model/Model.lua
src/model/Policy.lua

Change the 5-space indentation code in model.lua into 4-space indentation.

style: Adjust the format of the code and add things relate with policyMap

---

src/model/Policy.lua
tests/model/model_spec.lua

feat: Add function removePoliciesWithEffected

---

.github/luarocks-template.rockspec
.github/workflows/release.yml

This will generate and upload the latest rockspec of Casbin to LuaRocks on every new release.
@hsluoyz Can you please add a new secret to this repo as `LUAROCKS_API_KEY` with value as the API key from your LuaRocks account (more info [here](https://github.com/luarocks/luarocks/wiki/upload))? Since this needs an API key to work.

feat: Automated LuaRocks module release

---

.github/workflows/release.yml

The previous [run](https://github.com/casbin/lua-casbin/runs/3144807126) failed to upload the rockspec, hopefully this fixes it.

fix: LuaRocks module upload error

---

README.md

Fix: https://github.com/casbin/lua-casbin/pull/98#issuecomment-885976933

docs: Added badges for Lua/LuaRocks in README

---

src/persist/UpdateAdapter.lua

feat: Add UpdateAdapter

---

src/model/Model.lua
tests/model/model_spec.lua

feat: Add function copy

---

examples/subject_priority_model.conf
examples/subject_priority_model_with_domain.conf
examples/subject_priority_policy.csv
examples/subject_priority_policy_with_domain.csv
src/effect/DefaultEffector.lua
src/model/Model.lua
tests/main/enforcer_spec.lua

feat: Add function sortPoliciesBySubjectHierarchy

---

src/model/Policy.lua
tests/model/model_spec.lua

feat: Add function addPoliciesWithAffected

---

src/model/Assertion.lua
src/model/Model.lua
src/model/Policy.lua

feat: Add code relates with priorityIndex

---

src/main/CoreEnforcer.lua
src/model/Assertion.lua
src/model/Model.lua
src/model/Policy.lua
src/util/Util.lua

Add function copy in Assertion ,move deepCopy to Util and delete the old tableDeepCopy.

feat: Add copy in Assertion and move deepcopy to Util

---

src/main/CachedEnforcer.lua
src/persist/cache/Cache.lua
src/persist/cache/DefaultCache.lua

feat: Add Cache at persist

---

src/util/BuiltInFunctions.lua

fix: Add function validateVariadicArgs

---

src/util/BuiltInFunctions.lua
tests/util/built_in_functions_spec.lua

feat: Add keyMatch4

---

src/util/BuiltInFunctions.lua
tests/util/built_in_functions_spec.lua

feat: Add IPMatch

---

src/main/CoreEnforcer.lua
src/main/InternalEnforcer.lua
src/main/ManagementEnforcer.lua
src/persist/Dispatcher.lua
src/persist/WatcherUpdatable.lua

feat: Add interface in WatcherUpdatable.lua and Dispatcher.lua

---

src/main/InternalEnforcer.lua

feat: Add shouldpersist

---

src/main/InternalEnforcer.lua
src/persist/WatcherEx.lua

feat: Add function updateForAddPolicies and updateForRemovePolicies

---

src/main/InternalEnforcer.lua
src/main/ManagementEnforcer.lua
src/persist/file_adapter/FileAdapter.lua

feat: Add function updateFilteredPolicies

---

src/main/CoreEnforcer.lua

feat: Add function loadmodel

---

examples/rbac_model_matcher_using_in_op_bracket.conf
examples/rbac_policy_matcher_using_in_op_bracket.csv
src/model/Model.lua
tests/main/enforcer_spec.lua

Solve [#131](https://github.com/casbin/lua-casbin/issues/131)

feat: support bracket with in operator

---

src/model/Policy.lua
tests/model/model_spec.lua

Fixed the problem that policies will in a wrong order after call function updatePolicies

fix: fix updatepolicies

---

.github/luarocks-template.rockspec

Fix missing parts in PR: https://github.com/casbin/lua-casbin/pull/143

fix: upgrade luarocks release template, fix missing parts in PR: #143
